openapi: "3.0.0"
info:
  title: "Modelo para Fábrica e Contêineres"
  description: "Definições de entidades para modelar uma fábrica com setores e contêineres"
  version: "1.0.0"

components:
  schemas:

    Container:
      type: object
      properties:
        id:
          type: string
          description: "Identificador único do contêiner"
        type:
          type: string
          enum: ["Container"]
          description: "Define o tipo como 'Container'"
        container_code:
          type: object
          description: "Código do contêiner"
          properties:
            type:
              type: string
              enum: ["Property"]
            value:
              type: string
              description: "Código identificador do contêiner"
        container_volume:
          type: object
          description: "Volume do contêiner em litros"
          properties:
            type:
              type: string
              enum: ["Property"]
            value:
              type: number
              description: "Volume em litros"
        sectorId:
          type: object
          description: "Relacionamento com o setor a que pertence o contêiner"
          properties:
            type:
              type: string
              enum: ["Relationship"]
            object:
              type: string
              description: "ID do setor"
        active:
          type: object
          description: "Indica se o contêiner está ativo"
          properties:
            type:
              type: string
              enum: ["Property"]
            value:
              type: boolean
              description: "Estado de atividade do contêiner (true ou false)"

  # Caminhos de API
paths:
  /ngsi-ld/v1/entities:
    get:
      summary: "Obter entidades"
      responses:
        "200":
          description: "Lista de entidades"
          content:
            application/ld+json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: "Criar uma nova entidade"
      requestBody:
        description: "Dados da entidade a serem criados"
        content:
          application/ld+json:
            schema:
              $ref: "#/components/schemas/Factory"
      responses:
        "201":
          description: "Entidade criada com sucesso"
