openapi: "3.0.0"
info:
  title: "Modelo para Fábrica e Contêineres"
  description: "Definições de entidades para modelar uma fábrica com setores e contêineres"
  version: "1.0.0"

components:
  schemas:          

    Sector:
      type: object
      properties:
        id:
          type: string
          description: "Identificador único do setor"
        type:
          type: string
          enum: ["Sector"]
          description: "Define o tipo como 'Sector'"
        factoryId:
          type: object
          description: "Relacionamento com a fábrica a que pertence"
          properties:
            type:
              type: string
              enum: ["Relationship"]
            object:
              type: string
              description: "ID da fábrica"
        location:
          type: object
          description: "Localização geográfica do setor"
          properties:
            type:
              type: string
              enum: ["Point"]
            coordinates:
              type: array
              items:
                type: number
              description: "Coordenadas de latitude e longitude"
        containers:
          type: object
          description: "Contentores associados a este setor"
          properties:
            temperature:
              $ref: https://migcruzz.github.io/Factory_Public_Sample_Server/Factory/containers/containers.yaml
        
        porticos:
          MotionSensor:
            type: object
            required:
              -  MotionSensor
            allOf:
            - $ref: https://migcruzz.github.io/Factory_Public_Sample_Server/Factory/fiware_default/default_fiware_device.yaml

            description: >
              A device that consists of a sensor, has category `saref:Sensor` and is used for the purpose of sensing filling Level.
      
            properties:
              motion:
                $ref: https://migcruzz.github.io/Factory_Public_Sample_Server/Factory/fiware_default/saref-terms_default_fiware.yaml#/motion

  # Caminhos de API
paths:
  /ngsi-ld/v1/entities:
    get:
      summary: "Obter entidades"
      responses:
        "200":
          description: "Lista de entidades"
          content:
            application/ld+json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: "Criar uma nova entidade"
      requestBody:
        description: "Dados da entidade a serem criados"
        content:
          application/ld+json:
            schema:
              $ref: "#/components/schemas/Factory"
      responses:
        "201":
          description: "Entidade criada com sucesso"
